CFLAGS= -Wall -Werror -Wextra -pedantic -std=gnu89

all: 2-strlen.o 0-isupper.o 1-isdigit.o _putchar.o 9-strcpy.o 6-abs.o 5-strstr.o 4-strpbrk.o 4-isalpha.o 3-strcmp.o 3-puts.o 3-islower.o 2-strncpy.o 1-memcpy.o 1-strncat.o 2-strchr.o 100-atoi.o 0-strcat.o 0-memset.o

clean:
	rm -f 2-strlen.o 0-isupper.o 1-isdigit.o _putchar.o 9-strcpy.o 6-abs.o 5-strstr.o 4-strpbrk.o 4-isalpha.o 3-strcmp.o 3-puts.o 3-islower.o 2-strncpy.o 1-memcpy.o 1-strncat.o 2-strchr.o 100-atoi.o 0-strcat.o 0-memset.o 3-strspn.o 0-isupper.c 1-isdigit.c 2-strlen.c 3-strcmp.c 5-strstr.c main.h 0-memset.c 1-memcpy.c 2-strncpy.c 3-strspn.c 6-abs.c 0-strcat.c 1-strncat.c 3-islower.c 4-isalpha.c 9-strcpy.c _putchar.c 100-atoi.c 2-strchr.c 3-puts.c 4-strpbrk.c
